from google.genai import Client, types


def load_gemini_model(model_name: str) -> Client:
    """Load a Gemini model from Google GenAI API
    
    Args:
        model_name (str): Name of the Gemini model to load.
    """
    client = Client()
    return client

def generate_text(client: Client, prompt: str, model: str = "gemini-2.5-pro") -> str:
    """Generate text using the Gemini model
    
    Args:
        client (Client): The Gemini model client.
        prompt (str): The input prompt for text generation.
        model (str): The Gemini model to use.
        
    Returns:
        str: The generated text.
    """
    response = client.models.generate_content(
        model=model,
        contents=types.Part.from_text(text=prompt)

    )
    if response.text is None:
        raise ValueError("No text generated by the Gemini model.")

    return response.text